### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by gtrucollo** [kyleherzog/Blazicons.Lucide#1]
What is your plan to release this nuget package? i didn`t find yet.

**Comment by kyleherzog** [comment]
The intent is to release a NuGet package. However, this requires some changes at the core Blazicons level to make it work since this icon library is based on using stroke svg values instead of fill. All the other current Blazicons packages are fill based. I started looking at making the updates this week. I will provide updates once available.

**Comment by gtrucollo** [comment]
I appreciate the answer i will wait this release and i learn more about Blazicons funcionality for the contribute with this project

**Comment by kyleherzog** [comment]
The NuGet package for this has been released at https://www.nuget.org/packages/Blazicons.Lucide.
